# Import base image.
FROM python:latest

# The first parameter is file, the second is the path to place the file in the image.
ADD server.py /server/
ADD index.html /server/

# Working directory
WORKDIR /server/